# .github/FUNDING.yml

# Replace 'username' with your actual handles
github: [timtjoe]
patreon: timtjoe
ko_fi: timtjoe
buy_me_a_coffee: timtjoe
liberapay: timtjoe
custom: ['https://paypal.me/timtjoe']